#
# This Source Code Form is subject to the terms of the Mozilla Public License, v.
# 2.0 with a Healthcare Disclaimer.
# A copy of the Mozilla Public License, v. 2.0 with the Healthcare Disclaimer can
# be found under the top level directory, named LICENSE.
# If a copy of the MPL was not distributed with this file, You can obtain one at
# http://mozilla.org/MPL/2.0/.
# If a copy of the Healthcare Disclaimer was not distributed with this file, You
# can obtain one at the project website https://github.com/igia.
#
# Copyright (C) 2021-2022 Persistent Systems, Inc.
#

version: '3.5'


services:
    i2b2-etl:
        image: i2b2/i2b2-etl:v4
        container_name: i2b2-etl
        stdin_open: true
        tty: true
        environment:
            - I2B2_DS_CRC_IP=i2b2-mssql
            - I2B2_DS_CRC_USER=SA
            - I2B2_DS_CRC_PASS=<YourStrong@Passw0rd>
            - I2B2_DS_CRC_PORT=1433
            - I2B2_DS_CRC_DB=i2b2demodata
            # 
            - I2B2_DS_ONT_IP=i2b2-mssql
            - I2B2_DS_ONT_USER=SA
            - I2B2_DS_ONT_PASS=<YourStrong@Passw0rd>
            - I2B2_DS_ONT_PORT=1433
            - I2B2_DS_ONT_DB=i2b2metadata

            - CSV_DELIMITER=,
            - MAX_VALIDATION_ERROR_COUNT=10000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ${PWD}/data:/i2b2-cdi-qs/data
        ports:
            - 5000:5000
        networks:
            - i2b2-net
        command: ["python", "-m", "i2b2_cdi.loader.i2b2_cdi_app"]

networks:
    i2b2-net:
        name: i2b2-net
        driver: bridge
